### ISSUE TITLE
Support for specifying additional seeds parameter in values.yaml and cassdc resources

### ISSUE THREAD

**Issue by bradfordcp** [k8ssandra/roadmap#6]
`spec.additionalSeeds` is a foundational parameter for multi-region implementations. This should be surfaced up to `values.yaml` for initial exploration of multi-region deployments.

See [#547](https://github.com/k8ssandra/k8ssandra/issues/547)

**Comment by jdonenine** [comment]
This is now included as part of https://github.com/k8ssandra/roadmap/issues/1
